
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8620:3000"
    environment:
      - NODE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    networks:
      - app-network


  
networks:
  app-network:
    driver: bridge

volumes:
  db_data:

