name: Build, Test and Push Docker Image

on:
  push:
    branches: [ "master", "main", "develop" ]
  pull_request:
    branches: [ "master", "main", "develop" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/golang-app:latest .

      - name: Run unit tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/golang-app:latest go test ./...

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/golang-app:latest

  automated-api-tests:
    runs-on: ubuntu-latest
    needs: build-test-deploy
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "9178410-6f8bab6c-f595-4b3b-9012-c60e3b7ea416"
