name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-1 .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/db-1 .
          docker push ${{ secrets.DOCKER_USERNAME }}/web-1
          docker push ${{ secrets.DOCKER_USERNAME }}/db-1

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_IP }}
          username: linuxserver.io
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: whoami
