name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-1 ./web
          docker build -t ${{ secrets.DOCKER_USERNAME }}/db-1 ./db
          docker push ${{ secrets.DOCKER_USERNAME }}/web-1
          docker push ${{ secrets.DOCKER_USERNAME }}/db-1

      - name: Deploy to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}<< 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/web-1
          docker pull ${{ secrets.DOCKER_USERNAME }}/db-1
          docker-compose up -d
          EOF
